[package]
name = "kewb"
version = "0.1.0"
edition = "2021"
authors = ["LIOKA Ranraison Fiderana <luckasranarison@gmail.com>"]
license = "MIT"

[workspace]
members = ["cube", "two-phase", "cli"]

[dependencies]
cli = { path = "cli" }
cube = { path = "cube" }
two-phase = { path = "two-phase" }
